version: '3.3'

services:

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django_olympic
    command: bash -c "
      python /usr/src/SiteForOlympic/manage.py makemigrations &&
      python /usr/src/SiteForOlympic/manage.py migrate --noinput &&
      python /usr/src/SiteForOlympic/manage.py runserver 0.0.0.0:8001
      "
    volumes:
      - .:/usr/src/SiteForOlympic
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER = redis://redis:6379/0
      - CELERY_BACKEND = redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    command: bash -c "celery -A SiteForOlimpic worker -l INFO && celery -A SiteForOlimpic beat -l info"
    volumes:
      - .:/usr/src/SiteForOlympic
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  redis:
    image: "redis:alpine"


#volumes:
#  pgdata: