version: '3.3'

services:
  webapp:
    build: ./
    container_name: django_olympic
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app
    ports:
      - "1337:8001"
    env_file:
      - ./.env.dev

  flower:
    image: mher/flower
    environment:
      - FLOWER_PORT=8888
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "1338:8888"

  redis:
    image: "redis:alpine"
    restart: always

  worker:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - webapp
    env_file:
      - ./.env.dev
    command: 'celery -A SiteForOlimpic worker -l info'

  beat:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - webapp
      - worker
    env_file:
      - ./.env.dev
    command: 'celery -A SiteForOlimpic beat -l info'
