version: '3'

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn SiteForOlimpic.wsgi:application --bind 0.0.0.0:8001
    expose:
      - 8001
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod

  celery-worker:
    build: .
    restart: always
    command: celery -A SiteForOlimpic worker -l INFO
    env_file:
      - ./.env.prod

  celery-beat:
    build: .
    restart: always
    command: celery -A SiteForOlimpic beat -l INFO
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web


volumes:
  static_volume:
  media_volume: