version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn SiteForOlimpic.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 наружу
    expose:
      - 8000
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - "1337:80"
    depends_on:
      - web

  redis:
    image: "redis:alpine"
    restart: always

  flower:
    image: mher/flower
    environment:
      - FLOWER_PORT=5555
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"

  worker:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - web
    env_file:
      - ./.env.prod
    command: 'celery -A SiteForOlimpic worker -l info'

  beat:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - web
      - worker
    env_file:
      - ./.env.prod
    command: 'celery -A SiteForOlimpic beat -l info'

volumes:
  static_volume:
  media_volume:

# docker-compose -f docker-compose.prod.yml build
