# Generated by Django 4.2.1 on 2023-06-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=2000, verbose_name='Telegram id')),
                ('feedback', models.CharField(max_length=2000, verbose_name='Обратная связь')),
            ],
            options={
                'verbose_name': 'с',
                'verbose_name_plural': 'telegram_id',
                'ordering': ['telegram_id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=2000, verbose_name='Telegram id')),
                ('data_olymp', models.CharField(max_length=2000, verbose_name='Дата начала олимпиады')),
                ('subject', models.CharField(max_length=2000, verbose_name='Название предмета')),
                ('information', models.CharField(max_length=2000, verbose_name='Информация об олимпиаде')),
                ('rsoch', models.CharField(max_length=2000, verbose_name='Входит ли в перечень?')),
            ],
            options={
                'verbose_name': 'Подключенные уведомления',
                'verbose_name_plural': 'Подключенные уведомления',
                'ordering': ['telegram_id', 'data_olymp'],
            },
        ),
        migrations.CreateModel(
            name='Olympiads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2000, verbose_name='Предмет')),
                ('slug', models.SlugField(max_length=2000, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=2000, verbose_name='Название олимпиады')),
                ('information', models.CharField(max_length=2000, verbose_name='Информация по олимпиаде')),
                ('start', models.CharField(max_length=2000, verbose_name='Дата начала олимпиады')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрация',
                'ordering': ['title', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=2000, verbose_name='Telegram id')),
                ('data', models.CharField(max_length=2000, verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
                'ordering': ['telegram_id', 'data'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=2000, verbose_name='Telegram id')),
                ('full_name', models.CharField(max_length=2000, verbose_name='Имя пользователя')),
                ('blocked', models.CharField(max_length=2000, verbose_name='Заблокирован ли?')),
                ('data_registration', models.CharField(max_length=2000, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрация',
                'ordering': ['full_name', '-data_registration'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=2000, verbose_name='Telegram id')),
                ('help', models.CharField(max_length=2000, verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Обращения в помощь',
                'verbose_name_plural': 'Обращения в помощь',
                'ordering': ['telegram_id', 'help'],
            },
        ),
    ]
