# Generated by Django 4.2.1 on 2023-06-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['telegram_id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='notificationdates',
            options={'ordering': ['telegram_id', 'data_olymp'], 'verbose_name': 'Подключенное уведомление', 'verbose_name_plural': 'Подключенные уведомления'},
        ),
        migrations.AlterModelOptions(
            name='olympiads',
            options={'ordering': ['title', 'start'], 'verbose_name': 'Олимпиада', 'verbose_name_plural': 'Олимпиады'},
        ),
        migrations.AlterModelOptions(
            name='technicalsupport',
            options={'ordering': ['telegram_id', 'help'], 'verbose_name': 'Обращение в помощь', 'verbose_name_plural': 'Обращения в помощь'},
        ),
    ]
