# Generated by Django 4.2.3 on 2023-07-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='data_created',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания ссылки для сброса пароля'),
        ),
    ]
