# Generated by Django 4.2.3 on 2023-07-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_alter_resetpassword_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='data_created',
            field=models.DateField(verbose_name='Время создания ссылки для сброса пароля'),
        ),
    ]
