# Generated by Django 4.2.1 on 2023-06-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2000, verbose_name='Предмет')),
                ('slug', models.SlugField(max_length=2000, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='olympiads',
            name='information',
        ),
        migrations.RemoveField(
            model_name='olympiads',
            name='subject',
        ),
        migrations.AddField(
            model_name='olympiads',
            name='schedule',
            field=models.CharField(default='None', max_length=2000, verbose_name='Расписание олимпиады'),
        ),
        migrations.AddField(
            model_name='olympiads',
            name='site',
            field=models.CharField(default='None', max_length=2000, verbose_name='Сайт олимпиады'),
        ),
        migrations.AddField(
            model_name='olympiads',
            name='stage',
            field=models.CharField(default='None', max_length=2000, verbose_name='Этап олимпиады'),
        ),
        migrations.AddField(
            model_name='olympiads',
            name='sub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='olympic.subjects', verbose_name='Предмет'),
            preserve_default=False,
        ),
    ]
