# Generated by Django 4.2.3 on 2023-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0003_alter_resetpassword_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.CharField(max_length=2000, verbose_name='Пользователь'),
        ),
    ]
