# Generated by Django 4.2.1 on 2023-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0003_subjects_remove_olympiads_information_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['subject'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='olympiads',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=2000, unique=True, verbose_name='URL'),
        ),
    ]
