# Generated by Django 4.2.3 on 2023-08-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0004_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['customer'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='notificationdates',
            options={'ordering': ['customer', 'start'], 'verbose_name': 'Подключенное уведомление', 'verbose_name_plural': 'Подключенные уведомления'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['customer', 'data'], 'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплата'},
        ),
        migrations.AlterModelOptions(
            name='registrationsite',
            options={'ordering': ['customer', '-data_registration'], 'verbose_name': 'Регистрация Сайт', 'verbose_name_plural': 'Регистрация Сайт'},
        ),
        migrations.AlterModelOptions(
            name='resetpassword',
            options={'ordering': ['customer'], 'verbose_name': 'Сброс Пароля', 'verbose_name_plural': 'Сброс пароля'},
        ),
        migrations.AlterModelOptions(
            name='technicalsupport',
            options={'ordering': ['customer', 'help'], 'verbose_name': 'Обращение в помощь', 'verbose_name_plural': 'Обращения в помощь'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='notificationdates',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='registrationsite',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='resetpassword',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='technicalsupport',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='usernameandtelegramid',
            old_name='user',
            new_name='customer',
        ),
    ]
