# Generated by Django 4.2.1 on 2023-06-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0004_alter_subjects_options_alter_olympiads_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiads',
            name='slug',
            field=models.SlugField(max_length=2000, unique=True, verbose_name='URL'),
        ),
    ]
