# Generated by Django 4.2.1 on 2023-06-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0005_alter_olympiads_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationdates',
            options={'ordering': ['telegram_id', 'start'], 'verbose_name': 'Подключенное уведомление', 'verbose_name_plural': 'Подключенные уведомления'},
        ),
        migrations.RenameField(
            model_name='notificationdates',
            old_name='data_olymp',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='notificationdates',
            name='information',
        ),
        migrations.RemoveField(
            model_name='notificationdates',
            name='subject',
        ),
        migrations.AddField(
            model_name='notificationdates',
            name='schedule',
            field=models.CharField(default='None', max_length=2000, verbose_name='Расписание олимпиады'),
        ),
        migrations.AddField(
            model_name='notificationdates',
            name='site',
            field=models.CharField(default='None', max_length=2000, verbose_name='Сайт олимпиады'),
        ),
        migrations.AddField(
            model_name='notificationdates',
            name='stage',
            field=models.CharField(default='None', max_length=2000, verbose_name='Этап олимпиады'),
        ),
        migrations.AddField(
            model_name='notificationdates',
            name='sub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='olympic.subjects', verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationdates',
            name='title',
            field=models.CharField(default=0, max_length=2000, verbose_name='Название олимпиады'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationdates',
            name='rsoch',
            field=models.BooleanField(max_length=2000, verbose_name='Входит ли в перечень?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='blocked',
            field=models.BooleanField(max_length=2000, verbose_name='Заблокирован ли?'),
        ),
    ]
