# Generated by Django 4.2.1 on 2023-06-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0008_olympiads_rsoch'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNameAndTelegramID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=2000, verbose_name='Telegram id')),
                ('user', models.CharField(max_length=2000, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Соединение Телеграмм и Сайта',
                'verbose_name_plural': 'Соединение Телеграмм и Сайта',
                'ordering': ['telegram_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['user'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='notificationdates',
            options={'ordering': ['user', 'start'], 'verbose_name': 'Подключенное уведомление', 'verbose_name_plural': 'Подключенные уведомления'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['user', 'data'], 'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплата'},
        ),
        migrations.AlterModelOptions(
            name='technicalsupport',
            options={'ordering': ['user', 'help'], 'verbose_name': 'Обращение в помощь', 'verbose_name_plural': 'Обращения в помощь'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='telegram_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='telegram_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='technicalsupport',
            old_name='telegram_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='notificationdates',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='notificationdates',
            name='user',
            field=models.CharField(default=0, max_length=2000, verbose_name='Пользователь или его Telegram_ID'),
            preserve_default=False,
        ),
    ]
