# Generated by Django 4.2.1 on 2023-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0009_usernameandtelegramid_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
