# Generated by Django 4.2.1 on 2023-06-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0010_subjects_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='photo',
            field=models.ImageField(upload_to='static/images/subjects/', verbose_name='Фото'),
        ),
    ]
