# Generated by Django 4.2.1 on 2023-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0011_alter_subjects_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiads',
            name='slug',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='photo',
            field=models.ImageField(upload_to='subjects/', verbose_name='Фото'),
        ),
    ]
