# Generated by Django 4.2.1 on 2023-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0012_remove_olympiads_slug_alter_subjects_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=2000, verbose_name='Имя пользователя')),
                ('data_registration', models.CharField(max_length=2000, verbose_name='Дата регистрации')),
                ('email', models.CharField(default=None, max_length=2000, verbose_name='E-mail')),
                ('blocked', models.BooleanField(max_length=2000, verbose_name='Заблокирован ли?')),
            ],
            options={
                'verbose_name': 'Регистрация Сайт',
                'verbose_name_plural': 'Регистрация Сайт',
                'ordering': ['user', '-data_registration'],
            },
        ),
        migrations.RenameModel(
            old_name='Registration',
            new_name='RegistrationTelegram',
        ),
        migrations.AlterModelOptions(
            name='registrationtelegram',
            options={'ordering': ['full_name', '-data_registration'], 'verbose_name': 'Регистрация Телеграмм', 'verbose_name_plural': 'Регистрация Телеграм'},
        ),
    ]
