# Generated by Django 4.2.1 on 2023-07-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0013_registrationsite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=2000, verbose_name='Имя пользователя')),
                ('token', models.CharField(max_length=2000, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Сброс Пароля',
                'verbose_name_plural': 'Сброс пароля',
                'ordering': ['user'],
            },
        ),
        migrations.AlterModelOptions(
            name='olympiads',
            options={'ordering': ['sub', 'start'], 'verbose_name': 'Олимпиада', 'verbose_name_plural': 'Олимпиады'},
        ),
    ]
