# Generated by Django 4.2.3 on 2023-07-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0014_resetpassword_alter_olympiads_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, default=0, verbose_name='Время создания ссылки для сброса пароля'),
            preserve_default=False,
        ),
    ]
