# Generated by Django 4.2.1 on 2023-07-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0019_alter_resetpassword_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='data_created',
            field=models.DateTimeField(auto_now=True, null=None, verbose_name='Время создания ссылки для сброса пароля'),
        ),
    ]
