# Generated by Django 4.2.1 on 2023-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0020_alter_resetpassword_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='data_created',
            field=models.DateTimeField(auto_now=True, null='01/02/1981', verbose_name='Время создания ссылки для сброса пароля'),
        ),
    ]
