# Generated by Django 4.2.1 on 2023-07-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0022_alter_resetpassword_data_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpassword',
            name='data_created',
        ),
    ]
