# Generated by Django 4.2.1 on 2023-07-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0023_remove_resetpassword_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания ссылки для сброса пароля'),
        ),
    ]
