# Generated by Django 4.2.1 on 2023-07-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0025_alter_resetpassword_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='data_created',
            field=models.CharField(default='01/03/1981', max_length=2000, verbose_name='Время создания ссылки для сброса пароля'),
        ),
    ]
