# Generated by Django 4.2.1 on 2023-07-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0026_alter_resetpassword_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='data_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Время создания ссылки для сброса пароля'),
        ),
    ]
